site_name: VBlog

docs_dir: docs

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  
    # language: ru 
    
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - tags
  - blog
  - mermaid2

nav:
  - index.md
  - Blog:
    - blog/index.md
  - Code:
    - coding/hello-world.md
  - About:
    - about/about.md
    - Школа: about/school.md
  - Tags:
    - tags.md


